version: "3.4"
services:
  server:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - .:/work/
      - ./sankey/sankey:/usr/local/lib/python3.7/site-packages/sankey/:ro
    environment:
      DEBUG: 1
  test:
    build:
      context: .
      target: test
    volumes:
      - .:/work/
