version: "3.4"
services:
  server:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - .:/work/
    environment:
      DEBUG: 1
  test:
    build:
      context: .
      target: test
    volumes:
      - .:/work/
